src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 * @ORM\Table(name="invoices")
 */
class Invoice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $invoiceDate;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $invoiceNumber;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=InvoiceItem::class, mappedBy="invoice", cascade={"persist", "remove"})
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceDate(): ?\DateTimeInterface
    {
        return $this->invoiceDate;
    }

    public function setInvoiceDate(\DateTimeInterface $invoiceDate): self
    {
        $this->invoiceDate = $invoiceDate;

        return $this;
    }

    public function getInvoiceNumber(): ?string
    {
        return $this->invoiceNumber;
    }

    public function setInvoiceNumber(string $invoiceNumber): self
    {
        $this->invoiceNumber = $invoiceNumber;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|InvoiceItem[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(InvoiceItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setInvoice($this);
        }

        return $this;
    }

    public function removeItem(InvoiceItem $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getInvoice() === $this) {
                $item->setInvoice(null);
            }
        }

        return $this;
    }

    /**
     * @return int
     */
    public function getTotalBeforeTax(): int {
        $total = 0;
        foreach ($this->items as $item){
            $total += $item->getTotalBeforeTax();
        }
        return $total;
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Invoice;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('invoiceDate', DateType::class, [
                "label" => "Date de la facture",
                "widget" => "single_text"
            ])
            ->add('invoiceNumber', TextType::class, ["label" => "Numéro de la facture"])
            ->add('client', EntityType::class, [
                "class" => Client::class,
                "choice_label" => "name"
            ])
            ->add('items', CollectionType::class, [
                "entry_type" => InvoiceItemType::class,
                "allow_add" => true,
                "allow_delete" => true,
                "prototype" => true,
                "by_reference" => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/invoice")
 */
class InvoiceController extends AbstractController
{
    /**
     * @Route("/", name="invoice_index", methods={"GET"})
     */
    public function index(InvoiceRepository $invoiceRepository): Response
    {
        return $this->render('invoice/index.html.twig', [
            'invoices' => $invoiceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="invoice_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        // Interdit l'accès aux utilisateurs qui n'ont pas le rôle
        // ROLE_INVOICE_USER
        $this->denyAccessUnlessGranted("ROLE_INVOICE_USER");

        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_show", methods={"GET"})
     */
    public function show(Invoice $invoice): Response
    {
        return $this->render('invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="invoice_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Invoice $invoice): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_delete", methods={"POST"})
     */
    public function delete(Request $request, Invoice $invoice): Response
    {
        if ($this->isCsrfTokenValid('delete'.$invoice->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('invoice_index');
    }
}

templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('invoice_delete', {'id': invoice.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn">Delete</button>
</form>

templates/invoice/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.invoiceDate) }}
    {{ form_row(form.invoiceNumber) }}
    {{ form_row(form.client) }}

    <div>
        <h3>Lignes de facture</h3>
        <div class="text-right">
            <button type="button" id="btAddItem" class="btn btn-primary">
                Ajouter une ligne de facture
            </button>
        </div>

            {{ form_widget(form.items) }}

    </div>
<button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

<script>
    const $btAddItem = $("#btAddItem");
    const $itemContainer = $("#invoice_items");
    const template = $itemContainer.data("prototype");

    $btAddItem.on("click", function (){
        const $itemsNumber = $itemContainer.children().length;
        let html = template.replaceAll("__name__label__", "Ligne " + ($itemsNumber + 1));
        html = html.replaceAll("__name__", $itemsNumber);
        $itemContainer.append(html);
    });
</script>

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Invoice{% endblock %}

{% block body %}
    <h1>Edit Invoice</h1>

    {{ include('invoice/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('invoice_index') }}">back to list</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice index{% endblock %}

{% block body %}
    <h1>Invoice index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>InvoiceDate</th>
                <th>InvoiceNumber</th>
                <th>nb lignes</th>
                <th>Total HT</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
            <tr>
                <td>{{ invoice.id }}</td>
                <td>{{ invoice.invoiceDate ? invoice.invoiceDate|date('d/m/Y') : '' }}</td>
                <td>{{ invoice.invoiceNumber }}</td>
                <td> {{ invoice.items | length }} </td>
                <td> {{ invoice.totalBeforeTax }}</td>
                <td>
                    <a href="{{ path('invoice_show', {'id': invoice.id}) }}">show</a>
                    <a href="{{ path('invoice_edit', {'id': invoice.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_INVOICE_USER') %}
        <a href="{{ path('invoice_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Invoice{% endblock %}

{% block body %}
    <h1>Create new Invoice</h1>

    {{ include('invoice/_form.html.twig') }}

    <a href="{{ path('invoice_index') }}">back to list</a>
{% endblock %}

templates/invoice/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice{% endblock %}

{% block body %}
    <h1>Invoice</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ invoice.id }}</td>
            </tr>
            <tr>
                <th>InvoiceDate</th>
                <td>{{ invoice.invoiceDate ? invoice.invoiceDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>InvoiceNumber</th>
                <td>{{ invoice.invoiceNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('invoice_index') }}">back to list</a>

    <a href="{{ path('invoice_edit', {'id': invoice.id}) }}">edit</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}